### ISSUE TITLE
Its say redeemed on my account but all fake ? didnt receive also 

### ISSUE THREAD

**Issue by needhelp112** [neo-philipp/nitro-generator#1]
![image](https://user-images.githubusercontent.com/75563888/102055854-6f2f9200-3e26-11eb-90a3-0fe489d7a2cd.png)

**Comment by neo-philipp** [comment]
Hey @needhelp112 , thanks for showing me this issue. Could you please tell me what settings you were using in the config.json file? With that I mean if you've enabled or disabled checker, redeemer and notifications. Thanks

**Comment by needhelp112** [comment]
All default , all enabled

**Comment by needhelp112** [comment]
any idea?

**Comment by neo-philipp** [comment]
yeah i already have an idea. it's something with the request library most likely. I'm working on it rn

**Comment by needhelp112** [comment]
alright thanks ! lmk once you done

**Comment by neo-philipp** [comment]
hey @needhelp112 , I made some changes to both the checker.py and the main.py file. It is working for me, but it would be really great if you could test it for yourself and respond to me if its working before i close this issue. Thank you and appreciate it

**Comment by needhelp112** [comment]
![image](https://user-images.githubusercontent.com/75563888/102105048-dcb0e200-3e69-11eb-9fda-a729da89f90c.png)

**Comment by neo-philipp** [comment]
Ugh, python can be so annoying at times. Anyways, i think I've fixed it now. Please try it out again if you want. If you still have any error you can also message me on discord, where I can respond to messages a lot quicker. My tag there is neophilipp#9687

**Comment by needhelp112** [comment]
![image](https://user-images.githubusercontent.com/75563888/102110696-6fed1600-3e70-11eb-82a5-530f3487cd52.png)
like this means all good ?

**Comment by neo-philipp** [comment]
thats how its supposed to be, only problem is that you are being rate limited :/ . Im planning to include proxies for a future release, but that would take a while. If you have any experience in python you could fork this repo, improve and work on it and I'll merge it. For now I'll close this issue and if you like this tool I'd be really happy if you give it a star.
